FROM archlinux:latest

### Upgrade packages
RUN pacman --noconfirm -Syu

### Build packages
RUN pacman --noconfirm -S cmake base-devel

### Dev Libraries
RUN pacman --noconfirm -S qt6-base qt6-declarative
